### ISSUE TITLE
[Web] Vorschläge werden im Portal nicht aufgelistet

### ISSUE THREAD

**Issue by dANiiiiiEL** [AlternateLife/Bugs#1]
**Beschreibe den Fehler**
Beim Vorschläge-Tab, werden keine Vorschläge angezeigt. Das steht: "Keine Vorschläge für diesen Filter gefunden".

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1. Auf die Seite: https://portal.alternate-life.de/
2. Und auf: https://portal.alternate-life.de/suggestions

**Erwartetes Verhalten**
Mann sollte alle Vorschläge sehen können.

**Screenshots**
Screenshot: http://prntscr.com/mymfor

**System**
 - Betriebssystem: Windows 7
 - Browser: Google Chrome

**Weitere Informationen**
/

**Comment by romanzipp** [comment]
Wie die Meldung richtig aussagt, werden für den aktuellen **Filter** keine Ergebnisse gefunden. Stellt man im linken Menü andere Parameter ein, so sind Vorschläge zu finden.
