### ISSUE TITLE
Falsche Auto ausgeparkt

### ISSUE THREAD

**Issue by tonispielt** [AlternateLife/Bugs#102]
**Beschreibe den Fehler**
[Ich habe einen Trailer gekauft und meinen Transporter eingeparkt, ausparken konnte ich dann nur einen Stanier. Ich habe dann einen Stanier und den wieder eingeparkt. mein Auto hat sich geändert in der privaten Garage]

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1. Trailer gekauft
2. Fahrzeug eingeparkt
3. Anderes Fahrzeug wird in Garage angezeigt
4. eigenes Fahrzeug weg, neues Fahrzeug aus Garageninhalt da

**Erwartetes Verhalten**
[EEigentlich sollte das selbe Fahrzeug das ich eingeparkt habe auch in meiner Garage zum Ausparken möglich sein.]

**System**
 - Betriebssystem:  Windows 10
 - GTA Version: Steam 

**Weitere Informationen**
scheint datenbankfehler zu sein.
Mein Ingame Name ist Ronnie Schulz
Mein Forumsname ist RonnieS, damit ihr es nachvollziehen könnt in der DB

**Comment by Vleudex** [comment]
Ich habe das gleiche Problem, komischer Weise auch mit einem Stanier. (Ich selbst besitze einen Youga)
An öffentlicher Garage, ist das Ausparken von meinem Fahrzeug perfekt möglich.
