### ISSUE TITLE
[Kofferraum/Waffe/Duippen]

### ISSUE THREAD

**Issue by PunchFighter** [AlternateLife/Bugs#109]
Sobald man die Waffe in den Kofferraum tut und wieder rausholt,
dann verdoppelt sich die Munition, sobald man aber einen Relog macht,
wird die Waffe wieder ihren ganz normale Schuss anzahl zurück gesetzt.

Hierzu ein Clip von der Plattform Twitch:
https://clips.twitch.tv/BoredColdZucchiniMikeHogu

Ich hoffe das dieses als Erklärung gereicht hat.

System:
 - Betriebssystem: Windows 10 Home
 - GTA Version: Steam

**Comment by Cryma** [comment]
Wir speichern keine Munition, das bedeutet das diese sich nach dem Einlagern bzw. Auslagern wieder auffüllt. Das ist derzeit so gewollt.
