### ISSUE TITLE
Fremdes Auto in meiner Hausgarage

### ISSUE THREAD

**Issue by AMNEZIA68** [AlternateLife/Bugs#110]
**Beschreibe den Fehler**
In meiner Hausgarage befindet sich ein Fremdes Auto. Meine eigenen Fahrzeuge sind ganz normal in der öffentlichen Garage. 

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1. Einloggen
2. Hausgarage bedienen
3. Fremder Fahrzeug drin, in diesem Fall ein Stanier (siehe Anhang)

**Erwartetes Verhalten**
Keine Fremden Fahrzeuge in der eigenen Hausgarage.
Vllt. ist der Fehler im Trailerpark Sandyshores wegen der Mehrfachbenutzung pro Trailer? Bei mir im Trailer sind 2 weitere andere Teilnehmer nachträglich eingezogen.

**Screenshots**
https://i.imgur.com/wZeQefM.jpg

**System**
 - Betriebssystem: Windows 10
 - GTA Version: Steam

**Weitere Informationen**
Eventuell liegt es daran, dass sich nach meinem Kauf des Trailers, plötzlich 2 andere mit eingekauft haben?

**Comment by Cryma** [comment]
Siehst du immer noch fremde Fahrzeuge in deiner Garage?

**Comment by AMNEZIA68** [comment]
nein nicht mehr bis jetzt
