### ISSUE TITLE
Marker Garage fehlt

### ISSUE THREAD

**Issue by marschine** [AlternateLife/Bugs#111]
**Beschreibe den Fehler**
Bei meinem Haus ist die Garage zwar vorhanden und funktionstüchtig, allerdings fehlt der Marker für die Stelle zum ein/ausparken.

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1. Motel kaufen in Harmony
2. Auto dort einparken
3. Von Server disconnecten
4. Wieder auf Server connecten.

**Erwartetes Verhalten**
Marker der Garage als gelber Kreis sichtbar

**Screenshots**
http://prntscr.com/o5jjad

**System**
 - Betriebssystem: Win 10
 - GTA Version: Socialclub

**Comment by nick-strohm** [comment]
Duplikat von #10
