### ISSUE TITLE
Auto verschwunden nach Restart

### ISSUE THREAD

**Issue by Lebanesemagic** [AlternateLife/Bugs#112]
**Beschreibe den Fehler**
Meine Auto steht nicht in der Garage nach dem Serverrestart und nirgendwo anders auffindbar. 

**Reproduktion des Fehlers**
Ich hab das Auto heute abgeholt heute wurde es mir Überschrieben es geht um einen Sultan mit dem Kennzeichen PJK62CBM. Daraufhin sagte mir der Verkäufer ich müsste es nochmal in der Garage einparken hab ich daraufhin auch gemacht und konnte es ausparken. Danach hatte ich einen Unfall jemand von bennys sollte es abschleppen aber dann kam der Angekündigte Serverrestart. Daraufhin bin ich dann zur Garage da war er nicht aufzufinden danach hab ich nochmal einen Powernap vollzogen aber das Auto stand immer noch nicht in der Garage. Daraufhin wurde ich dann zu Bennys gefahren wo das Auto auch nicht aufindbar war und bist jetzt ist das Auto verschwunden.  

Erwartetes Verhalten
Eigentlich hätte das Auto nach dem Restart wieder in der Garage sein müssen weil ich der Besitzers des Autos bin. Es ist ein Sultan mit dem Kennzeichen PJK62CBM.

    System
 - Betriebssystem: Windows 10
 - GTA Version: Socialclub

Mit Freundlichen Grüßen
James Franklin

**Comment by Micky5991** [comment]
Das Fahrzeug befindet sich noch bei Bennys. Damit es bei dir in der Garage auftaucht *muss* es einmal in der persönlichen/öffentlichen Garage eingeparkt werden.
