### ISSUE TITLE
Fahrzeug nicht mehr in Garage auffindbar

### ISSUE THREAD

**Issue by Bababoi** [AlternateLife/Bugs#113]
**Beschreibe den Fehler**
Mein Fahrzeug wurde vor dem Ausloggen am Straßenrand abgestellt (am 23.06.2019 gegen ca. 3.00/3.30 Uhr. Nach dem Einloggen gegen ca. 13.30 Uhr bin ich zur nächstliegenden Garage gegangen und wollte mein Fahrzeug (Youga Classic mit Kennzeichen QV5RYGJ1) ausparken. Leider ist das Fahrzeug in der Garage nicht ersichtlich. Gecheckt wurde ebenfalls die Verwahrstelle in der nähe des Krankenhauses bei Rancha, dort ist leider auch nichts. Der Supporter "Juniorfisch | Robin" hat nachgesehen und konnte leider nichts machen. 

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
- konnte bisher nicht Reproduziert werden.

**Erwartetes Verhalten**
Fahrzeug sollte in der Garage ersichtlich sein und man sollte es Ausparken können.

**Screenshots**
Nicht gemacht 

**System**
 - Betriebssystem: Win 10 X64
 - GTA Version: Socialclub

**Weitere Informationen**
Derzeit noch keine weiteren infos.

**Comment by Micky5991** [comment]
Wie heißt dein Charakter?

**Comment by Bababoi** [comment]
Wambugu Dibababa

**Comment by Micky5991** [comment]
Dein Fahrzeug ist in der Garage bei Bennys. Nachdem dir diese dein Fahrzeug ausgehändigt haben, musst du es einmal in deiner persönlichen Garage einparken

**Comment by Bababoi** [comment]
Vergessen mit anzugeben: Ich hatte Gestern kurzzeitig ein Appartement / Hotezimmer gekauft und kurze Zeit später wieder Verkauft.

**Comment by Bababoi** [comment]
Danke
