### ISSUE TITLE
Sitzanimationen laut Tastenbelegung vertauscht.

### ISSUE THREAD

**Issue by KumasonArt** [AlternateLife/Bugs#114]
**Beschreibe den Fehler**
Laut Tastenbelegung ist das Sitzen auf Mauer "´" und sitzen auf dem Boden "Ä". Dies ist bei mir vertauscht.

**Charaktername / Namen der beteiligten Charaktere**
Kuma Takahashi

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1. ´ Drücken und
2. Ä drücken

**Erwartetes Verhalten**
Sitzanimationen sollten umgekehrt sein

**Screenshots**
Gibts nicht.

**System**
 - Betriebssystem: Win 10
 - GTA Version: Social Club

**Comment by nick-strohm** [comment]
In der aktuellen Tastenbelegung auf der Website ist `Ä` auf Mauern oder Stühlen sitzen und `´` auf dem Boden.

**Comment by KumasonArt** [comment]
My bad.
