### ISSUE TITLE
Verbindung zum Server in Dauerschleife.

### ISSUE THREAD

**Issue by HughWinters** [AlternateLife/Bugs#12]
- Verbindung zum Multiplayer geht sauber durch.
- RAGEMP läd sauber durch.

- Danach Blackscreen und unten, rechte in der Ecke der GTA Ladekreis. ENDLOS

- RAGEMP schon neu installiert
- Resources mehrfach gelöscht

**Erwartetes Verhalten**
Ich müsste eigentlich zur Char-Erstellung kommen.

**System**
 - Betriebssystem: Windows 10
 - GTA Version: Socialclub

**Comment by Micky5991** [comment]
Nach dem ersten Verbinden muss einmal das Spiel neu gestartet werden ohne die Resources zu löschen. Klappt das dann besser?

**Comment by HughWinters** [comment]
Jetzt hat es geklappt, obwohl ich alles so gemacht habe wie die letzte Stunde. 

Karma ;) Danke!
