### ISSUE TITLE
Standart Skin wenn mehrere Leute aufn Haufen sind

### ISSUE THREAD

**Issue by KikiStrange** [AlternateLife/Bugs#122]
### Beschreibe den Fehler
Wenn mehrere Leute auf einem Haufen sind, werden sie weiß und haben den Standart Skin von GTA

### Reproduktion des Fehlers
1. Viele Leute auf einem Haufen

### Erwartetes Verhalten
Man sollte halt den normalen Skin sehen

### Name der/des beteiligten Charakter(e)
Karma Hernandez

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: steam

**Comment by Cryma** [comment]
Das ist ein RageMP Problem.
