### ISSUE TITLE
Garage Unsichtbare Wand

### ISSUE THREAD

**Issue by Ehrgon** [AlternateLife/Bugs#125]
### Beschreibe den Fehler
Unsichtbare Barriere in Garage

### Reproduktion des Fehlers
1. In Garage reinfahren
2. Bis zur anderen Ausfahrt/Einfahrt fahren
3. Versuchen durchzufahren

### Erwartetes Verhalten
Man sollte durchfahren können oder es sollte sichtlich nicht möglich sein weiter zu fahren

### Weitere Informationen
https://youtu.be/TCyUSXH4axc reproduziert für Reportzwecke

### Name der/des beteiligten Charakter(e)
Hakan Kaya

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: steam

**Comment by Cryma** [comment]
Das ist ein Problem von GTA selber, darauf haben wir keinen Einfluss.
