### ISSUE TITLE
Rechnung kann nicht ausgestellt werden

### ISSUE THREAD

**Issue by huhnsoftware** [AlternateLife/Bugs#13]
**Beschreibe den Fehler**
[Eine klare Beschreibung des Fehlers.]

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1. ...
2. ...

**Erwartetes Verhalten**
[Eine Beschreibung des Verhaltens, welches eigentliche auftreten sollte.]

**Screenshots**
[Wenn nötig, füge Screenshots an um das Problem zu erklären.]

**System**
 - Betriebssystem: [z.B. Windows 10]
 - GTA Version: [Steam / Socialclub]

**Weitere Informationen**
[Füge weitere Informationen an, welche uns bei der Fehlersuche behilflich sein können.]

**Comment by Cryma** [comment]
Bitte noch einmal mit mehr Details.
