### ISSUE TITLE
Fehlende Garage

### ISSUE THREAD

**Issue by WismaDavis** [AlternateLife/Bugs#130]
### Beschreibe den Fehler
Im Motel in dem ich wohne war beim erstkauf die Garagenmarkierung da, danach nichtmehr.
Ich dachte die wurde entfernt bis ich andere dort ausparken gesehen habe.
Durch zufall habe ich gemerkt, dass lediglich die Garagenmarkierung fehlt aber der Rest noch funktioniert.

### Name der/des beteiligten Charakter(e)
Wisma Davis

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: socialclub

### Screenshots
![Alternate](https://user-images.githubusercontent.com/52210325/60109560-d8bb6c80-976a-11e9-8db8-184fc981dcf2.png)

**Comment by Cryma** [comment]
Ist mit dem nächsten Patch gefixt.
