### ISSUE TITLE
Garage beim Haus wird nicht angezeigt

### ISSUE THREAD

**Issue by neavalkonen** [AlternateLife/Bugs#131]
![Screenshot (532)](https://user-images.githubusercontent.com/52214295/60118633-0a3d3380-977d-11e9-809e-0c09befc55a1.png)
![Screenshot (533)](https://user-images.githubusercontent.com/52214295/60118653-1628f580-977d-11e9-9db1-1442cc745a1f.png)

### Beschreibe den Fehler
Motel Harmony, habe dort das Appartment gekauft, aber mir wird die Garage nicht mehr angezeigt. Direkt nach dem Kauf habe ich sie noch gesehen, jetzt leider nicht mehr. Öffentliche Garagen funktionieren normal.

### Weitere Informationen
Keine Ahnung ob das wichtig ist: Hatte kurz nach dem Kauf des Appartments mehrere Crashes (ging nach GTA Reparatur wieder weg). Wahrscheinlich ist es nur Zufall, aber ich wollte es zumindest erwähnt haben.

### Name der/des beteiligten Charakter(e)
Nea Valkonen

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: steam

**Comment by Cryma** [comment]
Dieser Bug ist mit dem nächsten Serverpatch behoben.
