### ISSUE TITLE
Fehlende Info anzeigen

### ISSUE THREAD

**Issue by 123undganzviele** [AlternateLife/Bugs#132]
### Beschreibe den Fehler
Wenn z.b. die Info Meldung "Ein neuer Dispatch ist verfügbar! Grund: Tankstelle geprellt" kommt, kann ich zwar im Leitstellen menu den neuen Dispatch anklicken, bekomme dann auf der Minimap ein Blip angezeigt wo das passiert ist.. aber bekomme keine info über das Kennzeichen oder den Betrag der geprellt wurde. Weiterhin ist mir aufgefallen das ich keine info zum gehalt bekomme. Ich bekomme laut Kontoauszug Gehalt aber das info Fenster erscheint nicht.

### Reproduktion des Fehlers
1. dispatch auswählen

### Erwartetes Verhalten
Es sollte sobald man einen Dispatch auswählt wird, der Ort auf der Minimap angezeigt werden und eine Meldung über der Minimap über das Kennzeichen und den Betrag der geprellt wurde.

### Weitere Informationen
Habe auch von anderen schon gehört das Sie keine Info Anzeige zu Gehalt oder Stütze bekommen.

### Name der/des beteiligten Charakter(e)
Jim Montel

### System
- Betriebssystem: Windows 10
- Browser: Firefox
- GTA Version: socialclub

**Comment by Cryma** [comment]
Nachdem du den Dispatch angenommen hast, müsstest du mehr Details dazu in Form einer Notification erfahren.

**Comment by 123undganzviele** [comment]
hat sich schon erledigt.. trotzdem danke !
