### ISSUE TITLE
Medic Dispatch

### ISSUE THREAD

**Issue by Skarfoze** [AlternateLife/Bugs#138]
### Beschreibe den Fehler
Ich hatte Heute die Situation wie ich im Dienst war das ich eine benachrichtigung bekommen habe für einen Dispatch aber mir auf der Karte keiner angezeigt worden ist.

### Name der/des beteiligten Charakter(e)
Dr. Haruto Takashima

### System
- Betriebssystem: Windows 10
- Browser: Firefox
- GTA Version: steam

**Comment by Cryma** [comment]
Hast du den Dispatch in dem Leitstellen-Menü angenommen?
