### ISSUE TITLE
Kriechen

### ISSUE THREAD

**Issue by Bomb3lbee** [AlternateLife/Bugs#139]
### Beschreibe den Fehler
Wenn man am Boden liegt und kriecht kann man trotzdem sein Handy benutzen

### Reproduktion des Fehlers
1. Man verliert soviel HP das man am Boden kriecht
2. Man holt sein Handy raus

### Erwartetes Verhalten
Ich denke mal das es nicht so sein sollte

### Name der/des beteiligten Charakter(e)
Fredd Kidd

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: steam

**Comment by Micky5991** [comment]
Doch, ließ die Regeln
