### ISSUE TITLE
Bug nach dem Einloggen

### ISSUE THREAD

**Issue by Zyssix** [AlternateLife/Bugs#14]
**Beschreibe den Fehler**
Nach dem einloggen und der Auswahl des Charakters bleibt man im Startbildschirm hängen.

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1. Einloggen
2. Charakter auswählen

**Erwartetes Verhalten**
Man sollte dann ins Spiel kommen

**Screenshots**
![BUG](https://user-images.githubusercontent.com/51856661/59552501-13adeb00-8f88-11e9-8b78-4757b8da2376.png)

**System**
 - Betriebssystem: [z.B. Windows 10]
 - GTA Version: Socialclub

**Weitere Informationen**
[Füge weitere Informationen an, welche uns bei der Fehlersuche behilflich sein können.]

**Comment by Cryma** [comment]
@Zyssix Besteht das Problem immer noch?

**Comment by Homy42** [comment]
Ich habe dasselbe Problem.

Habe mir zum Test einen Neuen Charakter erstellt mit dem das Problem nicht Reproduzierbar ist. Mit anderen Worten es muss an meinem Haupt Charakter liegen.

**Comment by Zyssix** [comment]
@Cryma also mit einem neu erstellten Charakter funktioniert es wieder aber anscheinend ist irgendwas mit meinem Hauptcharakter falsch das es immer im Startbildschirm hängen bleibt

**Comment by Zyssix** [comment]
eventuell mal die Charakter Position zurücksetzen lassen, vielleicht könnte das klappen
