### ISSUE TITLE
Kann auf meine Business E-mail keine mails empfangen

### ISSUE THREAD

**Issue by GauchoPanda** [AlternateLife/Bugs#140]
### Beschreibe den Fehler
Ich kann emails mit meiner Unternehmens mail senden aber nicht empfangen

### Reproduktion des Fehlers
1. Person A sendet mail
2. Im Mail Postfach des Unternehmens wird diese nicht angezeigt

### Erwartetes Verhalten
Man hätte eine Email bekommen sollen

### Weitere Informationen
Dies passiert nach auch bei privat mails wie ich IC erfahren habe

### Name der/des beteiligten Charakter(e)
John Stone

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: SocialClub

**Comment by romanzipp** [comment]
Sollte sich mit dem neuen Mailsystem erledigt haben
