### ISSUE TITLE
Toros Tuning Bug

### ISSUE THREAD

**Issue by Santez87** [AlternateLife/Bugs#145]
### Beschreibe den Fehler
Der Toros scheint aktuell ein Bug zu haben das die Tuningteile das Auto verlangsamen bzw plötzlich keine beschleunigung mehr existent ist.

### Reproduktion des Fehlers
EMS 3 oder 4
Renngetriebe oder Wettkampfgetriebe
Turbo

### Erwartetes Verhalten
Das Auto sollte keine leistung verlieren.

### System
- Betriebssystem: Windows 10
- Browser: Firefox
- GTA Version: socialclub

**Comment by Cryma** [comment]
Daran können wir leider nichts beeinflussen, das ist ein Problem von GTA V selber.
