### ISSUE TITLE
Kaution wird nicht zurückgezahlt.

### ISSUE THREAD

**Issue by VincentKiing** [AlternateLife/Bugs#146]
### Beschreibe den Fehler
Der Kräuterhändler stellt dir gegen 1.000 Dollar ein Fahrzeug zur Verfügung und nennt es "Kaution"

### Reproduktion des Fehlers
1. Kräuterhändler Job annehmen
2. Fahrzeug mieten
3. Fahrzeug zurückgeben

### Erwartetes Verhalten
Das Geld wieder in BAR zurückgeben!

### Name der/des beteiligten Charakter(e)
Vincent King

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: steam

**Comment by Cryma** [comment]
Das ist so gewollt, wird aber im nächsten Patch von `Kaution` zu `Gebühr` umbenannt, damit keine Verwirrung mehr aufkommt. Danke für die Meldung!
