### ISSUE TITLE
Munition beim Einlagern von Waffen wird erhöht

### ISSUE THREAD

**Issue by jeDekoo** [AlternateLife/Bugs#147]
### Beschreibe den Fehler
Es wurden 2 Waffen gekauft, und nacheinander in ein Auto gelagert. Eine Waffe wurde danach wieder herausgenommen und hatte mehr Munition als vorher.

### Reproduktion des Fehlers
1. Ein- und Auslagern der Waffe in ein Fahrzeug
2. Ein- und Auslagern der Waffe in eine Wohnung/Haus

### Erwartetes Verhalten
Waffe hätte die gleiche Anzahl an Munition wie nach dem direkten Kauf haben sollen.

### Name der/des beteiligten Charakter(e)
Tristan Löfgren

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: steam

**Comment by Cryma** [comment]
Wir speichern keine Munition, das bedeutet das diese sich nach dem Einlagern bzw. Auslagern wieder auffüllt. Das ist derzeit so gewollt.
