### ISSUE TITLE
Fahrzeug Coquette Classic mal Cabrio mal Coupe

### ISSUE THREAD

**Issue by Andrew1303** [AlternateLife/Bugs#149]
### Beschreibe den Fehler
Bei der Invetero Coquette Classic passiert es, dass das Fahrzeug manchmal ein Cabrio ist und manchmal ein Coupe. 
Ich habe es durch mehrfach ausparken auf das gekaufte Coupe korrigiert, allerdings bin ich gerade in das Galaxy (Mapchange) und wieder zurück nach draußen gegangen und aus dem Coupe wurde ein Cabrio. 

Das Fahrzeug passt hervorragend zu meinem Charakter und ich glaube bei Mackeones Communityserver ist dieser Fehler nicht aufgetreten.

### Reproduktion des Fehlers
1. Ein/Ausparken
2. Map wechseln - d.h. der eine sieht das Fahrzeug als Coupe, der andere als Cabrio
[Es handelt sich tatsächlich um das Coupe, nicht um ein geschlossenes Cabrio. Es sind grundverschiedene Fahrzeuge]

### Erwartetes Verhalten
Es sollte beim Coupe bleiben.

### Name der/des beteiligten Charakter(e)
Danny Walles

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: steam

**Comment by Micky5991** [comment]
Der Wechsel des Aussehens liegt daran, dass wir aktuell die Korrektur dieser Veränderung aus Stabilitätsgründen deaktiviert haben.
