### ISSUE TITLE
weibliche Sitzanimation für Stuhl ist fehlerhaft ("Frau" sitzt in der Luft)

### ISSUE THREAD

**Issue by Jarani85** [AlternateLife/Bugs#151]
![2019-07-06 22_06_48-RAGE Multiplayer](https://user-images.githubusercontent.com/51856151/60760736-d692c100-a03a-11e9-911a-ac01445b0241.png)
### Beschreibe den Fehler
Wenn man vor einem Stuhl steht, egal ob man vorher drauf gestanden hat und runter geht, oder direkt davor steht und "ä" drückt, sitzt die Dame nicht auf dem Stuhl, sonder schwebt davor in der Luft. Und zwar genau dort, wo die zuvor gestanden hat. Heißt, es werden nur die Beine angezogen.

### Reproduktion des Fehlers
Vor einen Stuhl oder ein Sofa stellen und "ä" drücken

### Erwartetes Verhalten
Charakter sollte sich auf die entsprechende Sitzfläche setzen und nicht in der Luft schweben

### Name der/des beteiligten Charakter(e)
Ivory Stokes

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: socialclub

**Comment by Micky5991** [comment]
Duplikat #124
