### ISSUE TITLE
Email Preview stimmt nicht mit verschickter Email überein

### ISSUE THREAD

**Issue by SkorPlays** [AlternateLife/Bugs#155]
### Beschreibe den Fehler
Emails können mit Markdown formatiert werden. Die Preview Funktion stellt Tabellen (Syntax in "weitere Infos") korrekt dar. Die verschickte Email kann diese jedoch nicht darstellen, da diese anscheinend keine "Markdown Here" unterstützung besitzt im gegensatz zur Preview Funktion

### Reproduktion des Fehlers
Markdown Tabellen Syntax in Email
-> Preview Funktion benutzen
-> Email verschicken

### Erwartetes Verhalten
Entweder sollte die Preview die Tabelle nicht zeigen oder die Email diese Darstellen können, jenachdem was eher gewüscht ist. Auf jeden Fall sollten beide überein stimmen.

### Weitere Informationen
Markdown Tabellen Syntax:
```
Spalte1| Spalte2 | Spalte3 
--- | --- | ---
Inhalt1_1 | Inhalt2_1 | Inhalt3_1
Inhalt1_2 | Inhalt2_2 | Inhalt3_2
```
Preview Darstellung:

Spalte1| Spalte2 | Spalte3 
--- | --- | ---
Inhalt1_1 | Inhalt2_1 | Inhalt3_1
Inhalt1_2 | Inhalt2_2 | Inhalt3_2

### Name der/des beteiligten Charakter(e)
Arthur Crownguard

### System
- Betriebssystem: Windows 10
- Browser: Firefox
- GTA Version: socialclub

**Comment by romanzipp** [comment]
Besteht der Fehler im aktuellen oder alten Mailsystem?
Die Tabelle sollte im aktuellen auf jeden Fall dargestellt werden, aber eine leicht andere Formatierung haben.

**Comment by SkorPlays** [comment]
Der Fehler war nur im alten System. im aktuellen funktionieren die Tabellen soweit. Wobei ich mir bei einer sache unsicher bin: Die Preview zeigt absätze an, ich glaube die entgültige Email tut dies aber nicht, wenn man nicht 2 hintereinander macht. was ich meine ist folgendes:

Gewolltes ergebnis:

> Hallo, 
> Mein Name ist SkorPlays
> 

wird glaube ich so angezeigt:

> Hallo, Mein Name ist SkorPlays

Um das zu fixen muss man also das ganze so schreiben: 

> Hallo, 
>
> Mein Name ist SkorPlays

**Comment by SkorPlays** [comment]
Übrigens kann man, wenn mein eine Email schreibt, Teile seines Texts nicht markieren um ihn zb. zu verschieben, zu kopieren oder zu löschen, was manchmal nervig ist, wenn man ganze absätze entfernen will. Ich weiß nicht ob das schon reportet wurde aber ich sags zur sicherheit mal.

**Comment by romanzipp** [comment]
Den ersten Fehler kann ich nicht reproduzieren, das sieht bei mir so aus:

![2019-07-18_14-44-58](https://user-images.githubusercontent.com/11266773/61458417-ba601f80-a96a-11e9-99b5-0cfef1747cc2.png)
![2019-07-18_14-44-48](https://user-images.githubusercontent.com/11266773/61458421-bb914c80-a96a-11e9-9f5f-65451623739e.png)
![2019-07-18_14-46-11](https://user-images.githubusercontent.com/11266773/61458447-cd72ef80-a96a-11e9-9719-c11ad8fdbb91.png)

Eigentlich es ist von Markdown aus gewollt, dass Zeilenumbrüche erst mit 4 Leerstellen am Ende einer Zeile oder 2 Zeilenumbrüchen dargestellt wird. Das haben wir zur Vereinfachung deaktiviert.

----

Zum zweiten Fehler: Ja, das ist momentan noch ein Anzeigefehler. Der Text wird zwar markiert aber es ist nicht sichtbar. Das fixe ich zeitnah

**Comment by SkorPlays** [comment]
Alles klar. Wie gesagt beim ersten war ich mir nicht sicher, da das im Alten so war. Vielen Dank.
