### ISSUE TITLE
Mappingfehler LSPD - Verhörräume

### ISSUE THREAD

**Issue by Nyndol** [AlternateLife/Bugs#158]
### Beschreibe den Fehler
Im gemappten Bereich des LSPD (Verhörräume) sind die Türen am Ende des Flures offen und wenn man hindurch geht bleiben die Türen dann verschlossen. Ergo: Der Spieler sitzt dort fest und kommt nicht wieder raus.

### Reproduktion des Fehlers
1. Durch die Türen im hinteren Bereich gehen
2. Nicht mehr durch die Türen zurück kommen können, da abgeschlossen.

### Erwartetes Verhalten
Die Türen sollten von Anfang an geschlossen sein bzw. nicht verschlossen sein, wenn man hindurchgeht.

### Weitere Informationen
[Füge weitere Informationen an, welche uns bei der Fehlersuche behilflich sein können]

### Name der/des beteiligten Charakter(e)
Darrel Colt

### System
 - Betriebssystem: Windows 10
 - GTA Version: Steam

**Comment by Cryma** [comment]
Das sollte mittlerweile nicht mehr vorkommen.
