### ISSUE TITLE
Schweißgerät beim Knastjob noch da

### ISSUE THREAD

**Issue by MRCStalker** [AlternateLife/Bugs#162]
### Beschreibe den Fehler
Laut dem Changelog vom 29.08. 19:15 sollte das Schweißgerät-Objekt deaktiviert sein. Das Objekt ist aber immernoch da.

https://s18.directupload.net/images/190711/dp5kyuik.png

### Reproduktion des Fehlers
1. In den Knast gehen
2. Schweißerjob annehmen
3. Zur Markierung laufen

### Erwartetes Verhalten
kein Schweißgerätobjekt beim Job

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: steam

**Comment by Cryma** [comment]
Das ist so korrekt. Das Schweißgerät, was du dort siehst, ist ein Teil von dem Schweiß-Szenario, was an den Punkten ausgeführt wird. Bei dem Changelog handelt es sich um das Schweißgerät, was man während den Laufwegen dabei hat.
