### ISSUE TITLE
Beim Tuning bekommt man hin und wieder eine fehlermeldung

### ISSUE THREAD

**Issue by WolfsHund23** [AlternateLife/Bugs#164]
### Beschreibe den Fehler
Hin und wieder wenn man was Tunen möchte kommt eine fehlermelden und mann kann ingame nix mehr machen bis man relogt hat

### Reproduktion des Fehlers
taucht random auf

### Erwartetes Verhalten
das tuning fenster hätte auf gehen sollen

### Name der/des beteiligten Charakter(e)
Fabian Freitag

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: steam

### Screenshots
http://prntscr.com/ofa0e7

**Comment by nick-strohm** [comment]
Duplikat #163

**Comment by MrTomboss** [comment]
![5191c7483ada84d032db4aa0ceea7dd7](https://user-images.githubusercontent.com/52867319/61236756-0cb9fa00-a739-11e9-8ed6-3ca118ac6d1d.png)

**Comment by MrTomboss** [comment]
Hier ein Screenshot der Fehlermeldung

**Comment by MrTomboss** [comment]
Mittlerweile bekomme ich den Fehler permanent egal wie oft ich den Client Resources Ordner lösche oder das Game neustarte.
