### ISSUE TITLE
La Mesa Tankstelle Mittelkonsole spinnt

### ISSUE THREAD

**Issue by p41nalta** [AlternateLife/Bugs#165]
### Beschreibe den Fehler
In der La Mesa Tankstelle spinnt die Mittelkonsole, wie ein Wackelkontakt, wenn den "E" Knopf auf der Tastatur drückt.

### Reproduktion des Fehlers
1. Die Mittleresäule testen (tanken).

### System
- Betriebssystem: Windows 10
- Browser: Firefox
- GTA Version: steam

**Comment by Micky5991** [comment]
Ich hab keine Ahnung was du mit "Wackelkontakt" und "Mittelkonsole" meinst

**Comment by p41nalta** [comment]
Es gibt ja 3 Zapfsäulen, die Mittlere reagiert manchmal nicht, wenn man "E" drückt. Ab und zu geht sie, nur dazu muss man öfters aus den Radios rausrennen und wieder rein.
 

Gesendet: Dienstag, 16. Juli 2019 um 09:52 Uhr
Von: "Francesco Paolocci" <notifications@github.com>
An: AlternateLife/Bugs <Bugs@noreply.github.com>
Cc: p41nalta <shitdreck@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [AlternateLife/Bugs] La Mesa Tankstelle Mittelkonsole spinnt und LKW Ausleihung (#165)


Ich hab keine Ahnung was du mit "Wackelkontakt" und "Mittelkonsole" meinst

**Comment by nick-strohm** [comment]
Ich nehme mal an die mittlere Zapfsäule ist nicht in der DB eingetragen und du bist im Radius der jeweils anderen Zapfsäulen.

**Comment by p41nalta** [comment]
Das kann natürlich sein.. Wusste ich nicht, wollte auch nur bescheid geben 😉 schön Tach noch! 
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 16.07.19, 10:08, Nick Strohm <notifications@github.com> schrieb:
Ich nehme mal an die mittlere Zapfsäule ist nicht in der DB eingetragen und du bist im Radius der jeweils anderen Zapfsäulen.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/AlternateLife/Bugs/issues/165?email_source=notifications\u0026email_token=AMT2E5QOG7PXUV3PGJ4SGLDP7V6ZTA5CNFSM4IDYTVZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2AB25A#issuecomment-511712628",

"url": "https://github.com/AlternateLife/Bugs/issues/165?email_source=notifications\u0026email_token=AMT2E5QOG7PXUV3PGJ4SGLDP7V6ZTA5CNFSM4IDYTVZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2AB25A#issuecomment-511712628",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Cryma** [comment]
Sollte mit dem nächsten Serverneustart behoben sein.
