### ISSUE TITLE
Mail-System

### ISSUE THREAD

**Issue by EmreXOXO** [AlternateLife/Bugs#166]
### Beschreibe den Fehler
Mails können nicht versendet werden.

### Erwartetes Verhalten
Mail hätte versendet werden sollen ggf. mit einer Bestätigung das dies geschehen ist.
Ebenso sollte die Mail unter "Gesendet" auftauchen bzw gespeichert werden.

### Name der/des beteiligten Charakter(e)
Emre Rafael Castro

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: socialclub

**Comment by EmreXOXO** [comment]
EDIT: Liegt wohl an folgender Fehlermeldung http://prntscr.com/offtrm
Kann natürlich sein das die Mail nicht mehr verfügbar ist, was mich jedoch wundern würde.

**Comment by romanzipp** [comment]
Die nicht-privaten Mailboxen müssen neu angelegt werden. Das betrifft Unternehmen und staatliche Adressen
