### ISSUE TITLE
Falsche Lieferscheine Am Hafen

### ISSUE THREAD

**Issue by R4past3r** [AlternateLife/Bugs#167]
### Beschreibe den Fehler
Hallo Liebes Projektteam, 

ich bin  mir nicht sicher ob es ein Fehler ist oder so gewollt, aber man bekommt am Hafen Lieferscheine die totaler unsinn sind und nicht zum Lieferort passen.
Ich habe heute einen Lieferschein bekommen auf dem streng geheim stand 1000 Waffen und diese sollte ich am West-highway an den Straßenrand stellen oder Spielzeug auf eine Baustelle liefern etc.

Sollte es so gewollt sein einfach ignorieren :)

### Reproduktion des Fehlers
Lieferschein holen

### Erwartetes Verhalten
Material und Ziel stimmig machen

### Name der/des beteiligten Charakter(e)
Dwayne Hayford

### System
- Betriebssystem: Windows 10
- Browser: Firefox
- GTA Version: socialclub

**Comment by Cryma** [comment]
Das ist so korrekt. Die Lieferscheine sind nur da, um damit RP zu machen.
