### ISSUE TITLE
Waffen illegal Einlagern 

### ISSUE THREAD

**Issue by Green42** [AlternateLife/Bugs#17]
**Beschreibe den Fehler**
Die illegalen Waffen können nicht bei den Autos in den  Kofferraum eingelagert werden nur die Legalen gehen .

 - Betriebssystem:  Windows 10
 - GTA Version: Socialclub]

**Comment by Micky5991** [comment]
Das ist so gewollt. Illegale Waffen können nicht mehr in Fahrzeuge eingelagert werden.
