### ISSUE TITLE
Fehler im Tuningmenü

### ISSUE THREAD

**Issue by Amy8792** [AlternateLife/Bugs#171]
### Beschreibe den Fehler
Sobald ich in das Tuner-menu rein gehe ist alles normal, aber wenn ich eine Kategorie auswählen will bekomme ich einen Error. Kann dann nichts mehr machen und muss das Game restarten. Es funktionieren dann auch keine Animationen mehr so das ich an Ort und stelle schon mal ausloggen muss um den Fehler zu beheben.

### Reproduktion des Fehlers
1. Beim Auto ins Menu über "L" rein gehen, Tuning auswählen, dann eine Kategorie z.b. Primärfarbe auswählen, Game freezed.
2. Bei Motorrädern ins Menu über "L" rein gehen, Tuning auswählen, dann eine Kategorie z.B. Frontstoßstange auswählen, Game freezed.
3. Bei beiden oben genannten ein Game Neustart gemacht. Danach ging es für eine Tuningoption, danach wieder das selbe Problem.
4. Client-Ressourcen gelöscht, danach ging es für 5 Tuning-Optionen und der Fehler kam wieder.

### Erwartetes Verhalten
Normal sollte ich entweder eine Vorschau machen können oder das Fahrzeug Tunen sollen.

### Name der/des beteiligten Charakter(e)
Amy Black

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: socialclub

### Screenshots
[http://prntscr.com/ogrjnn](url)

**Comment by Jarani85** [comment]
![unknown](https://user-images.githubusercontent.com/51856151/61464526-ad492d80-a976-11e9-89d5-0a8d4985aaa1.png)

Habe auch einen Fehler heute gehabt (2x).

Tuningmenü geöffnet, einen Punkt rausgesucht und bestätigt, da kam die Fehlermeldung. Konnte danach zwar wieder in das Spiel, jedoch absolut keine Menüs und Animationen mehr verwenden.

Relogg hat das Ganze behoben und man konnte weiter arbeiten.

**Comment by nick-strohm** [comment]
Duplikat #163
