### ISSUE TITLE
Items werden schneller verarbeitet als der Fortschritt Balken anzeigt

### ISSUE THREAD

**Issue by rtreeee** [AlternateLife/Bugs#172]
### Beschreibe den Fehler
Es wird mir links unten angezeigt die Gegenstände wurden verarbeitet bevor der Fortschritt Balken oben fertig war. Der Fehler beim Krümelteeverarbeiter und Fischhändler auf. Die Animation wird beendet und die Items sind verarbeitet und es kann die Verarbeitung von neuen Items gestartet werden. Die Fortschritt Anzeige läuft oben weiter beginnt aber von vorne wenn man wieder Items verarbeitet.

### Reproduktion des Fehlers
1. Verarbeiten bei Krümeltee oder mit dem Anglermesser einen Fisch filetieren.
2. Durch eine Windows Meldung oder Alt-Tab auf den Desktop und danach wieder InGame
3. Gegenstände werden scheinbar schneller verarbeitet als der Fortschritt Balken oben anzeigt, Fehler tritt meistens gegen Ende hin auf (90%).
4. Fehler trat durch setzen der Einstellung "Pause Game on Focus Loss" nicht mehr auf.

### Erwartetes Verhalten
Falls der Bug nur graphisch durch die Anzeige ist war alles richtig ansonsten hat er die Gegenstände schneller verarbeitet als er sollte. Er hätte weiterverarbeiten sollen bis die Fortschritt Anzeige fertig ist.

### Name der/des beteiligten Charakter(e)
John Criswall

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: steam

**Comment by Micky5991** [comment]
Ist nur ein Darstellungsfehler, wenn du während der Progressbar das Spiel minimierst o.ä., deshalb kein Bug
