### ISSUE TITLE
Die verschwundenen Köderboxen

### ISSUE THREAD

**Issue by MrTomboss** [AlternateLife/Bugs#174]
### Beschreibe den Fehler
Ich hab mir beim Angelhändler 7 Köderboxen gekauft. Nach einer weile war dann meine erste Box leer, nur das dann alle Boxen weg waren, sprich als die eine Leer ging, verschwanden alle.

### Reproduktion des Fehlers
1. Köderboxen kaufen
2. Guten Angelspot suchen
3. Angeln bis die Schwarte kracht
4. Statt einer brauchen sich alle Boxen auf

### Erwartetes Verhalten
Ich hätte noch 6 Köderboxen übrig haben sollen.

### Name der/des beteiligten Charakter(e)
James McCarter

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: socialclub

**Comment by Micky5991** [comment]
Duplikat von #143
