### ISSUE TITLE
Laggs bei der Anzeige des Ernährungsstatus

### ISSUE THREAD

**Issue by LeonoreReus** [AlternateLife/Bugs#178]
### Beschreibe den Fehler
Sobald eines der Zeichen rot aufblinkt fängt mein Spiel an zu laggen. Sobald ich etwas gegessen oder getrunken habe sind keine Laggs mehr da aber währendessen ist es wirklich unangenehm.

### Reproduktion des Fehlers
1. Hungerlevel droppen lassen
2. Durstlevel droppen lassen

### Erwartetes Verhalten
Laut Tamaaa sollte das so nicht sein deshalb hier den Report.

### Weitere Informationen
Ich kann mich gerne erkundigen ob Andere das Problem auch haben. Ich weiß, dass bei einem anderen Server sowas verhäuft mal aufgetreten ist, sodass sich die Dev's kurzerhand dafür entschieden haben das nicht mehr Interaktiv zu schalten sondern als bleibendes Symbol was lediglich die Farbe wechselt. Ich weiß aber nicht ob diese Info helfen kann, da Tamaaa auch sagte, dass das noch nie Probleme gemacht hat seitdem es Alternate Life gibt.

### Name der/des beteiligten Charakter(e)
Leonore Reus

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: steam

**Comment by Micky5991** [comment]
Prüfe deine Grafiktreiber und generelle Auslastung des PCs. Die benutzte Funktion ist eine einfache CSS Funktion und wir haben darauf keinen besonderen einfluss.
