### ISSUE TITLE
Welt wird unscharf dargestellt

### ISSUE THREAD

**Issue by HerrLades** [AlternateLife/Bugs#18]
**Beschreibe den Fehler**
Ingame wird das Spiel ab und an unscharf, als wenn plötzlich ein starker motion blur über das Spiel gelegt wird. Das Overley bleibt jedoch scharf. 

Im Singleplayer habe ich das Problem jedoch gar nicht. 

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1. Ingame gehen
2. Kamera drehen und den motion blur Effekt erleben

**Erwartetes Verhalten**
Ein beständig scharfes Bild

**Screenshots**
https://imgur.com/a/Qh8JDk2

**System**
 - Betriebssystem: Win 10
 - GTA Version: Steam

**Weitere Informationen**
[Füge weitere Informationen an, welche uns bei der Fehlersuche behilflich sein können.]

**Comment by Micky5991** [comment]
Das müssten Grafikeinstellungen sein. Vielleicht mal die Nachbearbeitung reduzieren. 

Wir sollten keinen Einfluss darauf haben

**Comment by HerrLades** [comment]
Stimmt. Ich wollte auch grade posten das es sich erledigt hat. Habe die Grafikeinstellungen auf Standard zurück setzt. Nun ist alles Fehlerfrei.
