### ISSUE TITLE
Peeper öffnet sich nicht

### ISSUE THREAD

**Issue by Ella-Maireen** [AlternateLife/Bugs#180]
### Beschreibe den Fehler
Wenn man Peeper öffnen möchte, öffnet sich die Seite nicht. Jedoch kommt man nicht mehr aus dem Menü raus, man muss also reloggen.

### Reproduktion des Fehlers
Peeper aufrufen

### Erwartetes Verhalten
Die Seite hätte sich öffnen müssen und man müsste es wieder beenden können.

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: steam

**Comment by romanzipp** [comment]
Ist gefixt
