### ISSUE TITLE
Fehlende Textur zwischen FIB und IAA Gebäuden im Brunnen

### ISSUE THREAD

**Issue by neunzen** [AlternateLife/Bugs#181]
### Beschreibe den Fehler
Es fehlt eine Textur im Brunnen zwischen FIB und IAA Gebäude.

### Reproduktion des Fehlers
1. Zu besagtem Ort fahren 
2. Textur in Richtung FIB Gebäude ladet nicht

### Erwartetes Verhalten
Die Textur sollte Laden so das man nicht durch die Map fallen kann.

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: steam

### Screenshots

https://imgur.com/a/BuhAf0s

**Comment by nick-strohm** [comment]
Irgendwelche Mods installiert? Wie sieht deine PC Auslastung aus (Taskmanager Performance Tab)?
