### ISSUE TITLE
Diverse Fehler bei der Charaktererstellung

### ISSUE THREAD

**Issue by Ramoth** [AlternateLife/Bugs#182]
### Beschreibe den Fehler
Bei der Erstellung eines neuen Charakters kommt es zu diversen Fehlern:
1. Die Zahlen unter der Schiebeleiste zeigen immer 0 an
2. im Punkt "Gesicht: Form und Farbe" haben die letzten Optionen bei Mutter und Vater jeweils keine erkennbare Veränderung zur Folge
3. "Gesichtsmerkmale" ist komplett leer bzw keine Optionen verfügbar
4. Die Auswahl eines Bartes (und dessen Farbe) ist überhaupt nicht möglich

### Reproduktion des Fehlers
Neuen Charakter erstellen

### Erwartetes Verhalten
Die oben genannten Auswahlmöglichkeiten sollten gegeben sein

### Weitere Informationen
Neuinstallation von Rage und den Clientdateien beheben den Fehler nicht

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: socialclub

**Comment by romanzipp** [comment]
Ich kann leider keine dieser Punkte reproduzieren. Hast du schon versucht, die Ordner im "client_resources" (im RAGE MP Verzeichnis) zu löschen?

**Comment by romanzipp** [comment]
Kann ich doch reproduzieren, wird gefixt
