### ISSUE TITLE
Anzeige auf Peeper "neue Peeps" nicht mehr vorhanden

### ISSUE THREAD

**Issue by Tranquillitus** [AlternateLife/Bugs#183]
### Beschreibe den Fehler
Seit dem letzten Serverdown heute 27.07.19 um 14:40 Uhr wird mir auf Peeper mit einem externen Browser nicht mehr angezeigt, dass neue Peeps erstellt wurden. Erst wenn ich die Seite manuell refreshe, sehe ich neue Peeps, die teilweise schon viele Minuten alt sind.

### Reproduktion des Fehlers
1) Peeper-Seite im Browser öffnen (z.B. Google Chrome) und offen lassen
2) warten auf neue Peeps
3) irgendwann manuell refreshen
4) sich über neue Peeps ohne Benachrichtigung wundern

### Erwartetes Verhalten
Anzeige mit "XY hat gepeept" oder "X neue Peeps vorhanden"

### Weitere Informationen
Vor dem letzten Serverdown ging alles wie gewohnt, hatte in der Zwischenzeit das Brownserfenster auch nicht geschlossen. Selbst bei Browser-Neustart die gleiche fehlende Anzeige, egal ob ich bei Peeper eingeloggt bin oder nicht.

### System
- Betriebssystem: Windows 10 1809
- Browser: Chrome
- GTA Version: steam

**Comment by Tranquillitus** [comment]
Auch getestet mit anderen Browsern und anderen Computern, angemeldet und nicht angemeldet, eine Benachrichtigung für neue Peeps kommt bei mir nicht mehr.

**Comment by romanzipp** [comment]
Konnte den Fehler reproduzieren, wir sehen und das an

**Comment by Tranquillitus** [comment]
Funktioniert bei mir wieder, besten dank.
