### ISSUE TITLE
Haus 2x Verkaufen

### ISSUE THREAD

**Issue by 1Muchi** [AlternateLife/Bugs#184]
### Beschreibe den Fehler
Ich habe am 26.07 eine neue Wohnung gekauft, die alte gekündigt. Habe dann gemerkt das ich 2 Paychecks lang Immobilien Steuer bezahle und meine Wohnung nochmal verkauft. Die 27.000$ die ich vom 2. Verkauf habe müssen demnach gelöscht werden bitte.

### Reproduktion des Fehlers
1. 1. Haus kaufen
2. 2. Haus kaufen
3. 1. Haus verkaufen

Da ich von einem Freund gehört habe, das er das Problem auch hat, denke ich es ist reproduzierbar.

### Erwartetes Verhalten
Das Haus hätte beim ersten verkauf verkauft sein sollen und ich hätte somit kein 2. x das Geld vom Verkauf bekommen sollen.

### Name der/des beteiligten Charakter(e)
Ivory Harper

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: socialclub

**Comment by Micky5991** [comment]
Ich konnte das zwar nicht in dem Unfang reproduzieren, aber ich habe evtl. einen Fall, wo das entstehen könnte.

Wenn das Problem weiterhin besteht, bitte melden.
