### ISSUE TITLE
Immobilien verkauf 2 mal möglich

### ISSUE THREAD

**Issue by SlycerBlack** [AlternateLife/Bugs#186]
![3HklLBOh](https://user-images.githubusercontent.com/53445594/62069422-84f3e580-b238-11e9-9ddc-cfd31a1a7e03.jpg)
### Beschreibe den Fehler
ich habe meine alte immobilie verkauft habe mir direkt danach eine neue gekauft und nach eine gewissen zeit bin ich an meiner alten immobilie vorbei gefahren da war das häuser symbol noch zu sehen und ich konnte es zum 2ten mal verkaufen

27.000 dollar sind zu viel auf meinem konto die müssten halt einfach gelöscht werden

### Reproduktion des Fehlers
eine immobilie verkaufen kurz danach direkt eine neue kaufen 
und nach einer gewissen zeit konnte ich meine alte immobilie wieder verkaufen

### Erwartetes Verhalten
das ich meine alte immobilie nur einmal verkaufen hätte dürfen

### Weitere Informationen
bilder von meiner alten immobilie sind im ersten ticket von mir drinnen wo ich auf dieses formular hingewiesen wurde

### Name der/des beteiligten Charakter(e)
Tyrees Kave

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: steam

**Comment by romanzipp** [comment]
Duplicate of #184
