### ISSUE TITLE
Bug beim Verkaufen von Häusern

### ISSUE THREAD

**Issue by Gojil** [AlternateLife/Bugs#189]
### Beschreibe den Fehler
Meine "Sozialwohnung" in Strawberry (EK 7500$) ist nach dem Verkauf weiterhin in meinem Besitz.
Ich kann weiterhin die Garage als auch die anderen Features der Wohnung nutzen.
Es scheint ebenfalls so, als wäre die Wohnung unendlich oft verkaufbar wodurch künstlich Geld generiert werden kann.
Die Steuer ist von der Immobilie weiterhin beeinflusst.

### Reproduktion des Fehlers
1. Wohnung Kaufen
2. Wohnung Verkaufen
3. Wohnung Verkaufen
4. "...

### Erwartetes Verhalten
Die Wohnung hätte nach dem Verkauf nicht mehr in meinem Besitz sein dürfen.

### Name der/des beteiligten Charakter(e)
Lance Walker

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: socialclub

**Comment by Micky5991** [comment]
Duplicate of #184
