### ISSUE TITLE
Repeep wird IC falsch angezeigt

### ISSUE THREAD

**Issue by MaylinDay** [AlternateLife/Bugs#190]
### Beschreibe den Fehler
http://prntscr.com/on2vy5 bekommt man einen Repeep wird IC angezeigt, dass man selbst dies getan hätte.

### Reproduktion des Fehlers
Wenn jemand meinen Peep repeeped.

### Erwartetes Verhalten
Der Name der Person hätte angezeigt werden müssen, nicht meiner.

### Weitere Informationen
http://prntscr.com/on2vy5

### Name der/des beteiligten Charakter(e)
Cathleen Torres

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: steam

**Comment by josiasmontag** [comment]
Ist gefixt
