### ISSUE TITLE
Keine Aktualisierung der Mails obwohl welche vorhanden sind

### ISSUE THREAD

**Issue by Tempelina42** [AlternateLife/Bugs#193]
### Beschreibe den Fehler
Keine Aktualisierung der Mails obwohl welche vorhanden sind.
Gespräch mit Fridolin. Ich wurde bereits aus dem Account entfernt und wieder eingefügt. Dies hat nicht geholfen.

### Weitere Informationen
Kein anderer hat Probleme mit dem Mailsystem. Bis gestern Abend ca. 03.00 lief alles Anstandslos. Anbei der aktuelle Stand der Mails, diesen sehe ich momentan 04.08.2019 20.00Uhr

### Name der/des beteiligten Charakter(e)
Dr. Stephanie  Steward

### System
- Betriebssystem: Windows 10
- Browser: Firefox
- GTA Version: steam

### Screenshots
![c766c6-1564941507](https://user-images.githubusercontent.com/5092856/62427432-18bf2900-b6f3-11e9-86fc-ccae2abe1ad3.png)

**Comment by romanzipp** [comment]
Ich erkenne hier keinen Fehler. Da sind alle Mails im Posteingang des Accounts.

**Comment by Tempelina42** [comment]
In der Mail von der Praxis sind aber noch neue dazugekommen, diese sieht auch Fridolin. Ich sehe die neuen nicht.

**Comment by romanzipp** [comment]
Es sind neue Mails reingekommen, die wurden aber in Ordner einsortiert - höchstwahrscheinlich von anderen Personen, die auf den Mail Account Zugriff haben.
