### ISSUE TITLE
Mirrorpark Teich Gebäude unsichtbare Wand

### ISSUE THREAD

**Issue by contiboll** [AlternateLife/Bugs#196]
### Beschreibe den Fehler
Im gebäude am Mirrorpark see ist im Haus eine unsichtbare wand ( http://prntscr.com/ooq1ll ) siehe foto

### Reproduktion des Fehlers
Reingehen und versuchen den Raum weiter zu betreten

### Erwartetes Verhalten
Selbsterklärend

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: steam

**Comment by Micky5991** [comment]
Das ist aktuell nicht änderbar. Der Bereich soll begrenzt sein und die Wand war zu GTMP Zeiten sichtbar.
