### ISSUE TITLE
Köderboxen beim Angeln werden gleichzeitig aufgebraucht

### ISSUE THREAD

**Issue by Quillo1896** [AlternateLife/Bugs#198]
### Beschreibe den Fehler
Wenn ich mit 2 Boxen a 75 köder das Angeln starte werden beide boxen gleichzeitig aufgebraucht, dies ist mir schon 2 mal passiert das dann beide weg sind sobald man null erreicht nicht das nur 1 dann weg ist

### Erwartetes Verhalten
Es hätte nur eine Box aufgebraucht werden sollen statt beide

### Name der/des beteiligten Charakter(e)
Grinko Gonzales

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: steam

**Comment by Micky5991** [comment]
Wie bereits dort beschrieben: Aktueller Workaround ist es, dass man die Boxen einzeln kauft und nicht x aufeinmal.

Duplicate of #143
