### ISSUE TITLE
Doppelt Geld erhalten nach Wohnungsverkauf

### ISSUE THREAD

**Issue by jamirojin123** [AlternateLife/Bugs#199]
### Beschreibe den Fehler
Nachdem ich eine Wohnung verkauft habe, hatte ich immernoch das symbol auf der Karte. Nach Neuloggen konnte ich die Wohnung erneut verkaufen. Da ich gucken wollte das ich das Geld für den verkauf nicht doppelt erhalten habe bin ich zur Bank gefahren. Dort ist mir aufgefallen das ich das Geld doppelt aufs Konto bekommen habe. Daher bitte ich darum das die 36.000 Dollar die ich zuviel auf das Konto durch den Doppelten Hausverkauf erhalten habe von meinem Konto zu löschen!

### Name der/des beteiligten Charakter(e)
Alejo Sanchez

### System
- Betriebssystem: Windows 7
- Browser: Chrome
- GTA Version: socialclub

**Comment by Micky5991** [comment]
Duplicate of #184
