### ISSUE TITLE
[Web] Startseite Banner auf 1440p

### ISSUE THREAD

**Issue by Wes9295** [AlternateLife/Bugs#2]
Mir ist aufgefallen, dass das Banner der Frontpage sich auf meinen 1440p Monitor verrutscht auf 1080p ist alles gut.

![chrome_8IiwVDytLX](https://user-images.githubusercontent.com/48801679/54766209-2e77fa00-4bfb-11e9-880b-8e67d943a92f.png)
![NVIDIA_Share_oYC5eulibI](https://user-images.githubusercontent.com/48801679/54766210-2e77fa00-4bfb-11e9-8ecd-68219c81bc3e.png)

**Comment by josiasmontag** [comment]
fixed
