### ISSUE TITLE
Kann als Medic im Dienst Leuten nicht aus der Down Phase helfen

### ISSUE THREAD

**Issue by Skarfoze** [AlternateLife/Bugs#202]
### Beschreibe den Fehler
Habe das Problem das ich niemanden mehr Hochhelfen kann und dann warten muss bis der Spieler Bewusstlos wird. Der Fehler dürfte erst seit 1 oder 2 tagen sein.

### Reproduktion des Fehlers
Jedes mal wenn ich bei jemanden bin der am Boden liegt und noch nicht Bewusslos ist.

### Name der/des beteiligten Charakter(e)
Dr. Haruto Takashima

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: steam

**Comment by Cryma** [comment]
Wird mit dem nächsten Patch gefixt.
