### ISSUE TITLE
Haus ist makiert und wird abgezogen (Steuern) kann es aber nicht verkaufen.

### ISSUE THREAD

**Issue by PandaASAP** [AlternateLife/Bugs#207]
### Beschreibe den Fehler
[Eine klare und nachvollziehbare Beschreibung des Fehlers]
Ich habe ein Haus in der Southside in einem Motel. Ich hatte dies ggekauft wollte es verkaufen doch das ging nicht. Nach weiterem schauen ist das Haus makiert auf dem CHarakter geschrieben aber ich kann es nicht verkaufen, sondern nur wieder kaufen. Trotzdem wird mir Stündlich die Haussteuer abgezogen.

### Reproduktion des Fehlers
Schritte, um den Fehler zu reproduzieren:
1. 
2. 

### Erwartetes Verhalten
Haus sollte verkaufbar sein.
Icon sollte verschwinden und Steuern sollten nicht mehr abgezogen werden.

### Weitere Informationen
[Füge weitere Informationen an, welche uns bei der Fehlersuche behilflich sein können]

### Name der/des beteiligten Charakter(e)
Jerome LeBrown]

### System
 - Betriebssystem: WIn10
 - GTA Version: Steam

### Screenshots
https://prnt.sc/or6p7g

**Comment by Micky5991** [comment]
Dort sind 2 Häuser, schau bitte, ob du das richtige erwischst. Wir schauen, dass wir eine bessere Erkennung des Eingangs implementieren.
