### ISSUE TITLE
Kokain führt zu Crashes

### ISSUE THREAD

**Issue by AMGSpirit** [AlternateLife/Bugs#213]
### Beschreibe den Fehler
Sobald man Kokain im Inventar auswählt, kommt eine Fehlermeldung, sodass keine Funktion mehr im Spiel möglich ist. Mann muss sich erneut einloggen, damit Sachen wie Handy zücken, Inventar aufrufen usw. wieder möglich sind. Ein Neustart behebt den Fehler nicht.

### Reproduktion des Fehlers
Inventar öffnen -> Kokain auswählen -> Ingame Oberfläche crasht

### Erwartetes Verhalten
Man hätte weitere optionen wie abpacken des Kokains, weitergeben usw. haben müssen, soweit kommt es allerdings nicht, da zuvor der besagte Fehler auftritt.

### Weitere Informationen
Weitere Sachen sind mir nicht aufgefallen. Es funktioniert alles. Alle Funktionen laufen problemlos, bis auf den besagten Crash der kompletten Ingame Oberfläche, sobald man das Kokain auswählt und bestätigt, dass man damit etwas machen möchte.

### Name der/des beteiligten Charakter(e)
Laroy Jackson

### System
- Betriebssystem: Windows 10
- Browser: Firefox
- GTA Version: socialclub

**Comment by Micky5991** [comment]
Siehe #211 und das ist kein crash, du hast eine Fehlermeldung im Hintergrund bekommen.
