### ISSUE TITLE
Fehlerhafte Formatierungen

### ISSUE THREAD

**Issue by MaylinDay** [AlternateLife/Bugs#218]
### Beschreibe den Fehler
Wenn man im Aktensystem PD-42 oder PD-44 eingibt, entsteht ein Fehler in der Verlinkung. Eigentlich sollten dort die Namen der aktuellen Polizisten stehen, allerdings tauchen dort die Namen der ehemaligen 42 und 44 auf, die mittlerweile in der Justiz tätig sind und deswegen wieder Aktenzugriff haben. 
http://prntscr.com/otiw1z

### Reproduktion des Fehlers
Man schreibt entweder PD-42 oder PD-44 in eine Akte. eigentlich sollten dann wie bei den P- oder F- eine Formatierung mit passendem Namen kommen, dies funktioniert aber nicht und zeigt falsche Namen an.

### Erwartetes Verhalten
Eigentlich sollten die Richtigen Namen da stehen, nämlich PD-42 Palle Pfaffmann oder PD-44 Ludwig O'Sullivan.

### Weitere Informationen
Das System kommt scheinbar nicht damit klar, dass entlassene Personen wieder eingestellt werden.

### Name der/des beteiligten Charakter(e)
Cathleen Torres

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: steam

**Comment by romanzipp** [comment]
Ist behoben
