### ISSUE TITLE
stresstest

### ISSUE THREAD

**Issue by Horujiru** [AlternateLife/Bugs#22]
**Beschreibe den Fehler**
Hallo mein Auto ein "ruiner" mach einen kick start Handbremse gas geben Handbremse losen Kickstar.
Auto hat höhstes Motor tuning 

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1. ...
2. ...

**Erwartetes Verhalten**
[Eine Beschreibung des Verhaltens, welches eigentliche auftreten sollte.]

**Screenshots**
![Kick start](https://user-images.githubusercontent.com/51856790/59552629-cd598b80-8f89-11e9-839e-23d9f39ab65c.JPG)
![Kick start 2](https://user-images.githubusercontent.com/51856790/59552631-cfbbe580-8f89-11e9-820c-743ad32a8d39.JPG)

**System**
 - Betriebssystem: [Windows 10]
 - GTA Version: [ Socialclub]

**Weitere Informationen**
[Füge weitere Informationen an, welche uns bei der Fehlersuche behilflich sein können.]

**Comment by Micky5991** [comment]
Das ist ein GTA Feature bei Muscle-Cars
