### ISSUE TITLE
ESC drücken lässt schneller verarbeiten/ablegen

### ISSUE THREAD

**Issue by SillyBottle** [AlternateLife/Bugs#223]
### Beschreibe den Fehler
Das Verarbeiten der Fische/Ablegen ins Fahrzeug wird verkürzt, wenn ich immer 2x ESC drücke.

### Reproduktion des Fehlers
1. Man geht zu einer Stelle wo man Angeln kann und angelt.
2. Man wartet bis ein FIsch anbeißt (Lieber warten bis ein großer Fisch ca. ab 5kg anbeißt, da es bei den kleinen eher nichts bringt)
3. Dann drückt man immer wieder ESC. Nicht schnell hintereinander ESC drücken, das habe ich auch schon ausprobiert und damit klappt es nicht, sondern 1x ESC, dann 1 Sek warten und dann wieder ESC.
4. Beim Einladen ins Fahrzeug genauso, wie in Punkt 3.

### Erwartetes Verhalten
Das Verarbeiten/Ablegen hätte normal bis 100% gehen sollen.

### Weitere Informationen
Ob das auch bei den ganzen Farmjobs geht kann ich nicht testen, wäre jedoch gut wenn man das auch mal mit denen machen würde (Kräuter, Salz etc.)
Bei den hinzugefügen Screenshots könnt ihr noch ein paar Prozent abziehen, da diese mit einer
kleinen Verzögerung von ein paar Millisekunden aufgenommen worden sind.

### Name der/des beteiligten Charakter(e)
Adrian Hopper

### System
- Betriebssystem: Windows 10
- Browser: Chrome
- GTA Version: Socialclub

### Screenshots

https://i.imgur.com/2gJS85z.jpg
https://i.imgur.com/wWprMDM.jpg
https://i.imgur.com/avZ4p3r.jpg
https://i.imgur.com/jjChlO4.jpg
https://i.imgur.com/bA61rPb.jpg

**Comment by Cryma** [comment]
Während du in dem ESC-Menü bist, wird einfach nur der Ladebalken pausiert. An der benötigten Zeit ändert das nichts.
