### ISSUE TITLE
falsche Fahrzeuge aus-/einparkbar 

### ISSUE THREAD

**Issue by Jarani85** [AlternateLife/Bugs#24]
**Beschreibe den Fehler**
Gerade bei Stein angefangen zu arbeiten, kann zusätzlich zum Rebel die Lehrlings und Gesellenfahrzeuge vom Holz ausparken.

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1. Job annehmen
2. Garage aufsuchen
3. Fahrzeuge auflisten lassen
4. Fahrzeug ausparken
5. geht mit einparken genauso

**Erwartetes Verhalten**
Es sollten nur die Fahrzeuge ausparkbar sein, die auch zum entsprechenden Job gehören

**Screenshots**
https://www.bilder-upload.eu/bild-02f8e5-1560609357.png.html

**System**
 - Betriebssystem: Win10
 - GTA Version: Socialclub]

**Weitere Informationen**
-/-

**Comment by Cryma** [comment]
Das wird bei dem Testserver so bleiben, sollte aber im nach dem Launch nicht mehr auftreten.
