### ISSUE TITLE
In Fahrzeug einsteigen, während man am Boden ist

### ISSUE THREAD

**Issue by romanzipp** [AlternateLife/Bugs#25]
**Beschreibe den Fehler**
Man kann in ein Fahrzeug einsteigen, während man am Boden ist

**Reproduktion des Fehlers**
https://clips.twitch.tv/SuspiciousDiligentTortoiseLitFam

**Comment by romanzipp** [comment]
Edit: Smartphone auch nutzbar

**Comment by Schikei** [comment]
https://cdn.discordapp.com/attachments/447416813052231690/589509331917996032/unknown.png
