### ISSUE TITLE
Waffe mit Motorrad auspackbar

### ISSUE THREAD

**Issue by AlexAkaAkamaru** [AlternateLife/Bugs#29]
**Beschreibe den Fehler**
aufm motorrad kann man schusswaffen auspacken und zielen, schießen geht nicht

Schritte, um den Fehler zu reproduzieren:
1. auf motorrad setzen
2. waffe auswählen per mausrad
3.zielen

**Erwartetes Verhalten**
sollte eig. nicht gehen/ waffe sollte nicht auspackbar sein als Fahrer

**Screenshots**
![Grand Theft Auto V Screenshot 2019 06 15 - 17 03 31 75](https://user-images.githubusercontent.com/51856429/59553101-4825a500-8f90-11e9-8f0d-c7e5769457f1.png)

**System**
 - Betriebssystem: WIN 10
 - GTA Version: [Steam / Socialclub]

**Weitere Informationen**
[Füge weitere Informationen an, welche uns bei der Fehlersuche behilflich sein können.]

**Comment by Micky5991** [comment]
Doch, auspackbar geht, schießen jedoch nicht. Das ist so gewollt
