### ISSUE TITLE
[Web] Footer auf der Datenschutzerklärung Seite, nimmt nicht die volle länge an.

### ISSUE THREAD

**Issue by TylerFiekens** [AlternateLife/Bugs#3]
**Beschreibe den Fehler**
Der Footer auf der Datenschutzerklärung-Seite nimmt nicht die volle Länge der Seite an.

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1. [Die Seite aufrufen](https://portal.alternate-life.de/legal/privacy)

**Erwartetes Verhalten**
Der Footer sollte die volle länge der Seite annehmen.

**System**
 - Betriebssystem: Windows 10
 - Browser: Chrome 73

**Weitere Informationen**
Das Problem liegt am `<b>` Tag, in dem der Footer liegt, ist dieser entfernt, nimmt der Footer die Volle länge ein.

**Comment by Micky5991** [comment]
Vielen Dank für die Meldung, der Footer sollte jetzt richtig dargestellt werden.
