### ISSUE TITLE
Hochhelfen Animation kann nicht unterbrochen werden

### ISSUE THREAD

**Issue by ThePixelbrain** [AlternateLife/Bugs#37]
**Beschreibe den Fehler**
Wenn jemand am Boden liegt und jemand versucht, der Person hochzuhelfen, dann kann die helfende Person nicht mit Taser davon abgehalten werden. (Taser unterbricht das Heilen nicht, Person wird durch Animation davor geschützt)

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1. Person A liegt am Boden
2. Person B hilft der Person hoch und führt dabei die Animation aus
3. Person C tasert die Person B
4. Person B heilt weiter

**Erwartetes Verhalten**
Die Animation wird unterbrochen und der Vorgang wird abgebrochen.

**System**
 - Betriebssystem: Windows 10
 - GTA Version: Socialclub
    (sollte aber irrelevant sein)

**Comment by Cryma** [comment]
In dem Fall sollte der helfende Spieler "E" drücken, um die Aktion abzubrechen.
