### ISSUE TITLE
Clientcrash nach großer "Kopfschmerzwelle" am Stadtpark

### ISSUE THREAD

**Issue by Jarani85** [AlternateLife/Bugs#39]
**Beschreibe den Fehler**
Eben gab es eine große Clientcrahswelle am Stadtpark. Nach dem Einloggen bekam ich entsprechende Fehlermeldung

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
- konnte bisher nicht reproduziert werden

**Erwartetes Verhalten**
[Eine Beschreibung des Verhaltens, welches eigentliche auftreten sollte.]

**Screenshots**
https://www.bilder-upload.eu/bild-27e7f4-1560614700.png.html

**System**
 - Betriebssystem: Windows 10]
 - GTA Version:  Socialclub]

**Weitere Informationen**
[Füge weitere Informationen an, welche uns bei der Fehlersuche behilflich sein können.]

**Comment by Micky5991** [comment]
Kannst du einmal die Datei `C:\RAGEMP\errf_log.txt` hier anhängen?

**Comment by Jarani85** [comment]
Den Ordnerpfad hab ich nicht und in meinem RageMP Ordner ist eine solche Datei nicht drin.

**Comment by Micky5991** [comment]
Dann schau mal bitte in deinen GTA Ordner, da könnte die Datei auch liegen

**Comment by Jarani85** [comment]
[errf_log.txt](https://github.com/AlternateLife/Bugs/files/3293979/errf_log.txt)
