### ISSUE TITLE
Cookie notice außerhalb des Containers (mobile) 

### ISSUE THREAD

**Issue by panteLx** [AlternateLife/Bugs#4]
**Beschreibe den Fehler**
Auf dem Handy (OnePlus 7 Pro, Chrome latest Version) wird die cookie notice außerhalb des Containers angezeigt (geht außerhalb des Bildes).

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1. Cookies löschen und website auf dem Handy anschauen

**Erwartetes Verhalten**
Denke mal, dass alles im Container bleibt. 

**Screenshots**
Keine

**System**
 - Betriebssystem: Android 
 - Browser: Chrome

**Weitere Informationen**
Keine

**Comment by josiasmontag** [comment]
Danke für den Hinweis, wir optimieren die AL Webseiten aber derzeit generell nicht für mobile Geräte.
