### ISSUE TITLE
Werkstatt Test Beekers

### ISSUE THREAD

**Issue by darkletsplayer** [AlternateLife/Bugs#43]
**Beschreibe den Fehler**
[Abschleppwagen kann man Kaufen, werden aber nicht in der Garage angezeit.
Leitstelle funktioniert nicht, bei uns wäre die Nummer 334334 diese geht aber nicht.]

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1. Werkstatt Menü und Abschleppwagen Kaufen.
2. Nummer versuchen anzurufen.

**Erwartetes Verhalten**

**Screenshots**

**System**
 - Betriebssystem: [z.B. Windows 10]
 - GTA Version: [Steam / Socialclub]

**Weitere Informationen**
[Füge weitere Informationen an, welche uns bei der Fehlersuche behilflich sein können.]

**Comment by Cryma** [comment]
@darkletsplayer Habt ihr die Nummer `334334` oder `069334334` getestet?

**Comment by darkletsplayer** [comment]
33343334

**Comment by darkletsplayer** [comment]
Alles klar 069 muss man schreiben dann funktioniert es.
