### ISSUE TITLE
TS ID wird nicht akzeptiert

### ISSUE THREAD

**Issue by plusyhsun** [AlternateLife/Bugs#48]
Ich benutze meine (Synchronisierte Standard )TS ID, welche auch auf vorherigen Servern angemeldet war/ist. Die Sicherheitsstufe ist 21 und der Server ist nebenbei aktiv bzw verbunden.
PureVoice ist aktiviert.
Auch mit einer anderen ID will es nicht klappen.
Folgende Meldung erscheint: "Du bist nicht zum Sever verbunden oder die eingegebene UID ist fehlerhaft"
(Server ist in der Übersetzung tatsächlich falsch geschrieben)
Meine Emailadresse ist bestätigt, sodass ich die ID jetzt zwangsläufig eingeben muss, um voran zu kommen.

 - Betriebssystem: [z.B. Windows 10]
 - Browser Version 75.0.3770.90 (Offizieller Build) (64-Bit)
-  TS 3.2.5. 
-  Qt 5.6.2
-  PureVoice 0.2.879.449

**Comment by Cryma** [comment]
Zu einem späteren Zeitpunkt noch einmal probieren. Derzeit ist unser System für die Verifizierung etwas überlastet.
