### ISSUE TITLE
private Garage nicht vorhanden

### ISSUE THREAD

**Issue by c2ho** [AlternateLife/Bugs#49]
**Beschreibe den Fehler**
Die zur Wohnung gehörende Garage ist weder über einen Marker noch über eine Interaktion verfügbar. Im Menü der Wohnung konnte auch kein Fahrzeug ausgeparkt werden.

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1. zur Wohnung gehen
2. Fahrzeug ausparken wollen
3. ???
4. kein Auto weil kein Marker oder Menüpunkt

**Erwartetes Verhalten**
Ich erwarte, dass ich mein Fahrzeug an der Wohnung ein- und ausparken kann.

**Screenshots**
https://imgur.com/2xKqM1A
(beim roten Kreis ist sonst immer ein gelber Marker-Kreis zum ein-/ausparken gewesen)

**System**
 - Betriebssystem: Windows 10 1809
 - GTA Version: Socialclub, aktuellste Version

**Weitere Informationen**
[unbekannt]

**Comment by josiasmontag** [comment]
Duplikat von #10
