### ISSUE TITLE
fehlende visuelle Effekte 

### ISSUE THREAD

**Issue by c2ho** [AlternateLife/Bugs#50]
**Beschreibe den Fehler**
Beim Haschkonsum gibt es keine visuellen Effekte.

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1. Hasch konsumieren
2. abwarten
3. kein visueller Effekt

**Erwartetes Verhalten**
bei Haschkonsum hab ich einen visuellen Effekt erwartet, wie es bei Blunts der Fall ist.

**Screenshots**
[sollte selbsterklärend sein]

**System**
 - Betriebssystem: Windows 10 1809
 - GTA Version: Socialclub

**Weitere Informationen**
[ - ]

**Comment by Cryma** [comment]
Nutzt du irgendeine Art von Grafik-Mods? Sei es Redux, Shader oder sonst irgendetwas?
