### ISSUE TITLE
Spieler hochhelfen per Cop-Menü keine Animation

### ISSUE THREAD

**Issue by ThePixelbrain** [AlternateLife/Bugs#52]
**Beschreibe den Fehler**
Wenn man einem Spieler mit L über das Cop-Menü hochhilft, dann hat man keine Animation, sonst funktioniert es allerdings normal.

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1. Combat Medic sein
2. Einem Spieler, der am Boden liegt per Cop-Menü (L und dann Spieler) hochhelfen
3. Proft??

**Erwartetes Verhalten**
Die gleiche Animation wie beim hochhelfen eines Spielers über das Spielermenü (M). Allerdings fehlt eine Animation gänzlich

**Comment by Cryma** [comment]
Das ist gewollt, die Medics wollten immer gerne ihre eigenen Animationen nutzen und es selber ausspielen.
