### ISSUE TITLE
Essen verbraucht sich nicht

### ISSUE THREAD

**Issue by ThePixelbrain** [AlternateLife/Bugs#55]
**Beschreibe den Fehler**
Wenn ich etwas esse oder trinke (getestet mit belegtem Brötchen, Durstlöscher, Wasser und Sandwich, vermutlich für jedes Item reproduzierbar), dann wird es nicht verbraucht. Die Animation findet ganz normal statt (während dieser Zeit habe ich auch keine Möglichkeit auf mein Inventar ö.Ä. zuzugreifen). Wenn ich jedoch etwas im Fahrzeug esse während ich fahre, dann bekomme ich die Notification, dass es verbraucht wurde, sonst passiert dies nicht. (Keine Ahnung, warum es gerade dann funktioniert..)

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1. Essen/Trinken kaufen
2. Inventar öffnen
3. ESSEN/TRINKEN!

**Erwartetes Verhalten**
Das Essen/Trinken wird beim Konsum verbraucht und verschwindet aus dem Inventar.

**System**
 - Betriebssystem: Windows 10
 - GTA Version: Socialclub

**Weitere Informationen**
Beim Beifahrer im Fahrzeug tritt das selbe auf, hat also nichts damit zu tun, dass ich der Fahrer bin.

EDIT: Es ist wohl nicht bei jedem Spieler reproduzierbar, was die ganze Sache noch spannender macht. Bei einigen funktioniert es weiterhin ordnungsgemäß, bei anderen aber nicht.

**Comment by VictoriaJames** [comment]
ich hatte es auch

**Comment by ThePixelbrain** [comment]
Okay, vergesst meinen Report. Ich habe gerade den Unterschied zwischen Essen/Trinken und Essen/Trinken aufbrauchen kennengelernt. Ist also nichtig der Report, sorry.
