### ISSUE TITLE
Bug nach dem Einloggen

### ISSUE THREAD

**Issue by Homy42** [AlternateLife/Bugs#57]
Nach dem Einloggen und der Auswahl meines Charakters bekomme ich ein verpixeltes Standbild was nicht mehr weg geht.

Schritte, um den Fehler zu reproduzieren:
1. Einloggen
2. Charakter Auswählen

**Screenshots**

![20190615173719_1](https://user-images.githubusercontent.com/51858818/59554785-140aae00-8fa9-11e9-9b3e-d66ddcdc9e66.jpg)

**System**
 - Windows 10]
 - GTA Version: Steam

**Weitere Informationen**
Ich habe mir zu Test zwecken ein neuen Charakter erstellt und habe versucht den Fehler bei mir zu Reproduzieren. Nach mehrfachen versuchen ist es mir nicht gelungen, es muss irgendwie an diesem Charakter hängen. Evtl. könnte ein Teleport oder Reset helfen ?

IC Name "Benjamin Hilton"

**Comment by josiasmontag** [comment]
Duplikat von #14
