### ISSUE TITLE
Haus hat kein Garagen Spawn mehr

### ISSUE THREAD

**Issue by Homy42** [AlternateLife/Bugs#58]
Bei meinem Haus was mir gehört aber auch Mitbewohner hat, finde ich keine Garage mehr.

Eigentlich müsste vor der Garage ein Gelber kreis sein der es mir ermöglicht meine eigenen Fahrzeuge auszuparken.

**Screenshots**

![20190615165141_1](https://user-images.githubusercontent.com/51858818/59554871-2afdd000-8faa-11e9-860d-f2d17326e8c9.jpg)

**System**
 - Betriebssystem: Windows 10
 - GTA Version: Steam

**Comment by josiasmontag** [comment]
Duplikat von #10
