### ISSUE TITLE
M Taste ruft Fehler hervor 

### ISSUE THREAD

**Issue by RealDealWilliams** [AlternateLife/Bugs#6]
Die M taste ruft einen Fehler hervor 
[Eine klare Beschreibung des Fehlers.]

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1. ...M drücken 
2. ...

**Erwartetes Verhalten**
[Eine Beschreibung des Verhaltens, welches eigentliche auftreten sollte.]

**Screenshots**
[Wenn nötig, füge Screenshots an um das Problem zu erklären.]
![Screenshot_153](https://user-images.githubusercontent.com/47720202/59552008-eb22f280-8f81-11e9-92f6-9621e2537e90.png)

**System**
 - Betriebssystem: Windows 10
 - GTA Version: Socialclub

**Weitere Informationen**
[Füge weitere Informationen an, welche uns bei der Fehlersuche behilflich sein können.]

**Comment by RealDealWilliams** [comment]
M taste funktioniert nach Update

**Comment by Cryma** [comment]
Sollte mittlerweile behoben sein.
