### ISSUE TITLE
Gebrauchtwagenhändler spawnt keine Autos

### ISSUE THREAD

**Issue by huhnsoftware** [AlternateLife/Bugs#65]
**Beschreibe den Fehler**
[Eine klare Beschreibung des Fehlers.]
Nach Kauf beim Gebrauchtwagenhändler in Paleto Bay wird kein Auto gespawnt.

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1. Ein Auto kaufen
2. Sehen, dass kein Auto spawnt

**Erwartetes Verhalten**
[Eine Beschreibung des Verhaltens, welches eigentliche auftreten sollte.]
Eigentlich sollte das gekaufte Fahrzeug spawnen.

**Screenshots**
[Wenn nötig, füge Screenshots an um das Problem zu erklären.]

**System**
 - Betriebssystem: [z.B. Windows 10]
 - GTA Version: [Steam / Socialclub]

**Weitere Informationen**
[Füge weitere Informationen an, welche uns bei der Fehlersuche behilflich sein können.]

**Comment by Tranquillitus** [comment]
Wird das Auto nicht automatisch in die Garage platziert?

**Comment by Cryma** [comment]
Das was @Tranquillitus sagt.
