### ISSUE TITLE
Polizei/Mediziner Fahrzeugschlüssel verloren nach Gamecrash

### ISSUE THREAD

**Issue by onionreaper** [AlternateLife/Bugs#68]
**Beschreibe den Fehler**
Man hat keinen Zugriff mehr auf die Fahrzeuge nach einem Gamecrash während man im Dienst ist.

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1. Man hat einen Crash
2. Kein Zugriff mehr zum Fahrzeug

**Erwartetes Verhalten**
Man sollte eigentlich den Zugriff behalten.

**System**
 - Betriebssystem: Windows 10
 - GTA Version: Steam

**Weitere Informationen**
Gibt keine ;)

**Comment by Cryma** [comment]
Der Bug sollte mittlerweile gefixt sein.
