### ISSUE TITLE
M - Taste Spielermenü

### ISSUE THREAD

**Issue by Klipminx** [AlternateLife/Bugs#7]
M - Taste Spielermenü
Sobald ich ingame die Taste M drücke Friert das game ein, es kommt ein Windows Fehler Signalton und das Spiel crashed

**Reproduktion des Fehlers**
Habe es 2x nacheinander versucht mit dem Selben ergebnis. Nach dem versuch des aufrufens des Spielermenüs stürzt das spiel ab

**Erwartetes Verhalten**
Es müsste ein Menü auftauchen indem ich Spielinterne Funktionen und Aktionen Finde

**Screenshots**
-

**System**
 - Betriebssystem: Windows 10
 - GTA Version: Steam 

**Weitere Informationen**
-

**Comment by Klipminx** [comment]
Reproduktion des Fehlers
M drücken

**Comment by Cryma** [comment]
Sollte mittlerweile behoben sein.
