### ISSUE TITLE
Fehler beim Festnehmen von Zivilisten.

### ISSUE THREAD

**Issue by Pray611** [AlternateLife/Bugs#70]
**Beschreibe den Fehler**
Cop nimmt Zivilisten fest & legt im Handschellen an ( festnehmen )
wenn dann der festgenommene Zivilist zu Boden geht (bsp. mit einem Baseballschläger ausgeknockt wird ) & dieser Zivilist wieder aufgehoben wird (spieler hochhelfen ) wird diesem Zivilist unten neben der Sprachweite beim UI zwar das Handschellen Zeichen angezeigt aber es ist ihm möglich Animation auszuführen und das Handy vollständig zu nutzen ( waffen sind NICHT auswählbar .

**System**
 - Betriebssystem: z.B. Windows 10
 - GTA Version: Steam

**Comment by Cryma** [comment]
Duplikat #56
