### ISSUE TITLE
Ausparkgarage Walker Autohaus defekt

### ISSUE THREAD

**Issue by Yuilicious** [AlternateLife/Bugs#71]
hallo,

ich wurde bei walker eingestellt um den Spielern die Möglichkeit zu geben die Autos zu testen, allerdings nach ca 15 Autos kann ich nicht mehr auf die Garage zugreifen. Ich kann zwar Autos im büro kaufen aber sie nicht mehr ausparken. 

Nach mehrmaligem Neustart und reccoursen ordner löschen funktionierte es immer noch nicht :C

**Comment by Yuilicious** [comment]
ging kurze Zeit wieder, jetzt gehts wieder nicht mehr <3

**Comment by Cryma** [comment]
Ich konnte das jetzt nicht reproduzieren. Gibt es bestimmte Fahrzeuge, bei denen das nicht funktioniert?
