### ISSUE TITLE
stresstest

### ISSUE THREAD

**Issue by Potterr1** [AlternateLife/Bugs#72]
**Beschreibe den Fehler**
wenn man am boden ist kann man noch auto fahren

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1. sich ausnocken lassen
2. versuchen mit dem auto weg zu fahren

**Erwartetes Verhalten**
sollte man ohne hilfe eig. nicht wieder ins auto steigen können

**System**
 - Betriebssystem: Windows 10
 - GTA Version: Socialclub

**Weitere Informationen**
[Füge weitere Informationen an, welche uns bei der Fehlersuche behilflich sein können.]

**Comment by Cryma** [comment]
Duplikat #25
