### ISSUE TITLE
Fläche um Verarbeiter etwas zu groß.

### ISSUE THREAD

**Issue by neunzen** [AlternateLife/Bugs#73]
**Beschreibe den Fehler**
[Die Fläche um den Yin-Zentee Verarbeiter ist etwas groß]

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1. Zum Verarbeiter fahren.

**Erwartetes Verhalten**
[Man Sollte nicht zu weit weg von einem Verarbeiter Stehen können und verarbeiten.]

**System**
 - Betriebssystem: [Windows 10]
 - GTA Version: [Steam]

**Comment by Micky5991** [comment]
Dies wurde von den Spielern gewünscht, deshalb ist dort alles korrekt.
