### ISSUE TITLE
Taser unterbricht heilen nicht 

### ISSUE THREAD

**Issue by marschine** [AlternateLife/Bugs#81]
**Beschreibe den Fehler**
Während eine Person sich mit einem ErsteHilfeKasten heilt, kann dies durch den Taser nicht unterbrochen werden. Die Person heilt sich einfach weiter, fällt nicht um und ist nach Ablauf der Animation dann Full Life als wäre nichts passiert. 

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1: Person A benutzt ErsteHilfeKasten
2: Person B tasert Person A währenddessen

**Erwartetes Verhalten**
Vermutlich sollte der Heilen-Prozess durch den Taser abgebrochen werden, ansonsten ist die Heilende Person während dem Heilen quasi Immun dagegen. 

**System**
 - Betriebssystem:  Windows 10
 - GTA Version: Socialclub

**Weitere Information:**
Relatiert vermutlich:
https://github.com/AlternateLife/Bugs/issues/37

**Comment by Cryma** [comment]
Duplikat #37
