### ISSUE TITLE
JVA Ausgang umpositionieren, frühzeitige Entlassung mit Fehlern

### ISSUE THREAD

**Issue by Nexus92TTV** [AlternateLife/Bugs#82]
**Beschreibe den Fehler**
Der Entlassungs-Checkpoint (Exit, für Gefangene) sollte mit dem Minijob-Schweißen-Checkpoint getauscht werden, da dieser sich mehr in Richtung des Ausgangs befindet. 
Des Weiteren, sofern ein Gefangener frühzeitig entlassen wird, ist es nicht möglich über den Entlassungs-Checkpoint (Exit, für Gefangene) zu nehmen, sondern man müsste den Gefangenen über das Treppenhaus aus der JVA geleiten.

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1. Ein Gefangener muss in der JVA inhaftiert sein
2. Ein Officer mit einem Mindestrang der mir nicht geläufig ist (ich war zu der Zeit Chief) muss den Gefangenen vorzeitig entlassen.

**Erwartetes Verhalten**
Der Gefangene sollte die JVA über den vorgesehenen Ausgang verlassen können.

**Weitere Informationen**
Der Checkpoint Wechsel wäre nur optional, allerdings sollte das frühzeitige Entlassen funktionieren

**Comment by Cryma** [comment]
Wenn ein Officer einen Gefangen frühzeitig entlässt, soll er das auch vernünftig ausspielen und selber aus der JVA führen.
