### ISSUE TITLE
Crash Vespuccikanäle & Umgebung 

### ISSUE THREAD

**Issue by Aergerlich** [AlternateLife/Bugs#86]
**Beschreibe den Fehler**
Game Crash in Vespuccikanäle & Umgebung

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
Mit dem Auto durch Vespucci 

**Erwartetes Verhalten**
Kein Crash

**Screenshots**
http://prntscr.com/o2i1nd 

Hier fand der Crash statt 

**System**
 - Betriebssystem: Windows 10
 - GTA Version: Steam

**Comment by Micha3lSchiggy** [comment]
Hatt den fehler auch. Bei mir war es des öffteren wenn ich mit dem Auto einen Unfall gebaut hab oder eine Person schaden genommen hat.
