### ISSUE TITLE
Crashscreenshots

### ISSUE THREAD

**Issue by Micky5991** [AlternateLife/Bugs#88]
Bitte hinterlasst hier screenshots von den Orten wo ihr Crashes bekommt. 

**Karte und vielleicht noch aus dem Spiel**

**Comment by ThePixelbrain** [comment]
![2019 06 16-15 12_01](https://user-images.githubusercontent.com/19214217/59564640-71563c00-9049-11e9-8f2e-8e519f7ad3aa.png)

**Comment by LXVII-BHZ** [comment]
![CXaLGKh](https://user-images.githubusercontent.com/51882363/59565169-1b38c700-9050-11e9-802b-081c83be0e87.jpg)
![jlBjhJr](https://user-images.githubusercontent.com/51882363/59565171-20961180-9050-11e9-9275-45a96a0f689d.jpg)
