### ISSUE TITLE
Während des benutzten eines Erste-Hilfe-Kasten auto fahren

### ISSUE THREAD

**Issue by Nyndol** [AlternateLife/Bugs#89]
**Beschreibe den Fehler**
Momentan ist es möglich sich zu heilen und dabei Auto zu fahren.

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1. Sich neben die Fahrertür stellen
2. Einen Erste-Hilfe-Koffer nutzen
3. F drücken um ins Fahrzeug zu gelangen
4. Z drücken zum Motor starten
5. Los fahren. Dabei läuft der Balken zum heilen weiter.

**Erwartetes Verhalten**
Wenn man einen Erste-Hilfe-Koffer benutzten, sollte man während der Animation dafür bzw. während der Balken voll läuft nichts anderes mehr machen sollen.

**System**
 - Betriebssystem: Windows 10
 - GTA Version: Steam

**Weitere Informationen**
Könnte sein dass der Fehler schon bestand als der Server noch aktiv war.

**Comment by Cryma** [comment]
@Nyndol Ich kann den Fehler nicht reproduzieren. Wenn ich den Erste-Hilfe-Koffer nutze, kann ich nicht in ein Fahrzeug einsteigen. Kannst du dich vielleicht noch an irgendetwas erinnern, dass du währenddessen noch getan hast?

**Comment by Nyndol** [comment]
Merkwürdig, ich frage nochmal nach um absolut sicher zu gehen. Aber eigentlich haben wir es genauso, Schritt für Schritt mit bis zu 3 Leuten ausprobiert wo es dann funktioniert hat.

**Comment by Nyndol** [comment]
Kleines Update: Werde auf dem Live Server ab morgen dann ein Auge drauf halten. Wenn ich es wieder hinbekomme melde ich mich noch mal.

**Comment by Cryma** [comment]
Falls es reproduziert werden kann, bitte noch einmal ein Issue mit einer genauen Beschreibung aufmachen.
