### ISSUE TITLE
Keine Characterauswahl

### ISSUE THREAD

**Issue by SugarPalli** [AlternateLife/Bugs#9]
Hallo,
ich starte Rage ganz normal, komme auch zum logg in Fenster,
gebe meine Daten ein, er nimmt die auch an,
danach kommt komplettes Standbild, keine Characterauswahl möglich.
Habe Rage neu installiert und es klappt trotzdem nicht.
Mein Char wurde zum Flughafen zurück gesetzt, weiß nicht ob es damit
etwas zu tun hat. Ich kann also nicht ingame, da ich nach dem logg in
nichts mehr machen kann.
War im Support bei Robin er meinte das können nur die Deffs machen.

![standbild](https://user-images.githubusercontent.com/51856299/59552320-b153eb00-8f85-11e9-9c4a-1885e567b45a.PNG)

**Comment by Micky5991** [comment]
Versuchs bitte erneut, sollte jetzt besser gehen

**Comment by SugarPalli** [comment]
perfekt danke
