### ISSUE TITLE
Anmelden / Passwort vergessen funktioniert nicht richtig

### ISSUE THREAD

**Issue by fragkp** [AlternateLife/Bugs#94]
**Beschreibe den Fehler**
Als ich mich heute versucht habe anzumelden konnte ich dies nicht mehr, da angeblich mein Passwort falsch wäre. Das würde ich jetzt mal ausschließen, da ich 1Password zum speichern verwenden habe.
Als nächstes habe ich dann versucht mein Passwort zurücksetzen, was auch erst funktioniert. Ich werde danach automatisch angemeldet.
Wenn ich mich dann aber wieder abmelde und wieder anmelden möchte - gleich Problem.

**Reproduktion des Fehlers**
1. Abmelden und versuchen anzumelden.
2. Passwort zurücksetzen und mit dem neuen Passwort anmelden -> Funktioniert nicht

**System**
 - Windows 10
 - Neuster Chrome

**Comment by romanzipp** [comment]
Bitte melde dich im Support, da es ein Problem speziell mit deinem Account sein wird
