### ISSUE TITLE
Syncprobleme

### ISSUE THREAD

**Issue by Micha3lSchiggy** [AlternateLife/Bugs#95]
**Beschreibe den Fehler**
Sync Probleme am Stadtpark und am PD

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
schwierig...

**Screenshots**
https://clips.twitch.tv/TentativeSteamyBaconCoolCat

**System**
 - Betriebssystem: Windows 10
 - GTA Version: aktuell

**Weitere Informationen**
Der Fehler ist bei mir nur gegen 21 Uhr aufgetreten. Danach lief es gut.

**Comment by Micky5991** [comment]
Das war gestern ein extremfall, das sollte im Normalbetrieb nicht auftreten.
