### ISSUE TITLE
Der Timer fürs Aufheben wird nicht unterbrochen bspw. durch Tazer

### ISSUE THREAD

**Issue by Nexus92TTV** [AlternateLife/Bugs#96]
**Beschreibe den Fehler**
Während man eine Person, die am Boden liegt, aufheben möchte, dann kann der Timer selbst durch einen Tazerschuss nicht gestoppt werden. Animation wird abgebrochen, aber die Person wird weiterhin aufgehoben.

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1. Eine Person die auf dem Boden liegt, aber noch bei Bewusstsein ist.
2. Eine weitere Person, die die am Boden liegende Person aufheben möchte
3. Eine dritte Person, die die zweite Person tazert.

**Erwartetes Verhalten**
Der Timer zum Aufheben der Person sollte unterbrochen werden.

**Comment by Cryma** [comment]
Duplikat #37
