### ISSUE TITLE
Mapping des Gerichtsgebäudes fehlerhaft

### ISSUE THREAD

**Issue by ThePixelbrain** [AlternateLife/Bugs#98]
**Beschreibe den Fehler**
Das Interior des IAA-Towers ist nicht richtig gemappt. Wenn man durch den Teleporter am Gerichtsgebäude geht, landet man dort. Man kann allerdings durch alle Glaswände (bis auf die beim ersten Büro) hindurch gehen, alle Büroräume bis auf das Erste sind leer. Bei den leeren Büroräumen ist außerdem die Stadt nicht sichtbar, wenn man aus dem Fenster guckt. Desweiteren kann man die Glaswände zerstören, d.h. man kann sich aus dem Fenster stürzen.

**Reproduktion des Fehlers**
Schritte, um den Fehler zu reproduzieren:
1. Zum Gerichtsgebäude fahren und Teleporter benutzen
2. Im IAA Tower (wo man automatisch nach Teleport landet) rumlaufen
Um aus dem Fenster zu springen:
1. Fenster zerstören (durch gegenspringen, kaputt schlagen/schießen)
2. Rausfallen/-springen
3. Definitiv kein Profit mehr

**Erwartetes Verhalten**
Alle Büroräume sollte Interior haben, man sollte durch Glaswände nicht durchlaufen können. Außerdem sollte man vielleicht nicht suizidal aus dem Fenster eines Wolkenkratzers springen können. (oder vielleicht gerade doch? 🤔)

**Screenshots**
Glaswände ohne Kollision: https://streamable.com/0nxna
Suizidales aus dem Fenster springen: https://streamable.com/9tp46

**System**
 - Betriebssystem: Windows 10
 - GTA Version: Socialclub

**Comment by Micky5991** [comment]
Das Gerichtsgebäude sieht genau so aus, wenn es keine Mapveränderung enthält. Wir sind gerade dabei dafür etwas zu organisieren oder eine Alternative zu suchen.
